
flash:
	haxelib run lime test -minify project.xml flash -j16
html5:
	haxelib run openfl test -minify project.xml html5 -j16 -Ddom
neko:
	haxelib run openfl test -minify project.xml neko -j16
android:
	haxelib run lime test project.xml android -j16 -Dlegacy
ios:
	haxelib run lime test project.xml ios -j16 -Dlegacy -simulator
