
flash:
	haxelib run lime test -minify project.xml flash -j16
neko:
	haxelib run lime test -minify project.xml neko -j16 -Ddom
html5:
	haxelib run lime test -minify project.xml html5 -j16 -Ddom -dce full
android:
	haxelib run lime test project.xml android -j16 -Dlegacy
ios:
	haxelib run lime test project.xml ios -j16 -Dlegacy -simulator
